export const config = {
  BASE_PATH: process.env.REACT_APP_DEV_API_BASE_PATH,
  USER_REGISTER: process.env.REACT_APP_DEV_API_AUTH_USER_REGISTER,
  USER_LOGIN: process.env.REACT_APP_DEV_API_AUTH_USER_LOGIN,
  COOKS: process.env.REACT_APP_DEV_API_COOK_GET_ALL_COOKS,
  PENDING_COOKS: process.env.REACT_APP_DEV_API_COOK_GET_ALL_PENDING_COOKS,
  COOK_CREATE_PROFILE: process.env.REACT_APP_DEV_API_COOK_CREATE_PROFILE,
};
