export const config = {
  BASE_PATH: process.env.REACT_APP_DEV_API_BASE_PATH,
  USER_REGISTER: process.env.REACT_APP_DEV_API_AUTH_USER_REGISTER,
  USER_LOGIN: process.env.REACT_APP_DEV_API_AUTH_USER_LOGIN,
  COOKS: process.env.REACT_APP_DEV_API_COOK_GET_ALL_COOKS,
  PENDING_COOKS: process.env.REACT_APP_DEV_API_COOK_GET_ALL_PENDING_COOKS,
  COOK_CREATE_PROFILE: process.env.REACT_APP_DEV_API_COOK_CREATE_PROFILE,
  MENU: process.env.REACT_APP_DEV_API_MENU_BASE_PATH,
  COOK: process.env.REACT_APP_DEV_API_MENU_BY_COOK,
  MENU_CREATE_DISH: process.env.REACT_APP_DEV_API_MENU_CREATE_DISH,
  MENU_UPDATE_DISH: process.env.REACT_APP_DEV_API_MENU_UPDATE_DISH,
  MENU_DELETE_DISH: process.env.REACT_APP_DEV_API_MENU_DELETE_DISH,
  MENU_ADD_DISH_TO_MEAL: process.env.REACT_APP_DEV_API_MENU_ADD_DISH_TO_MEAL,
};
